completed css-brochure-form
KennethDelaCruz/c0121-code-solutions pull request #16
Opened 2021-01-21 01:56 UTC by KennethDelaCruz

![image](https://user-images.githubusercontent.com/69921839/105269454-cf61d400-5b48-11eb-865c-f84d2a08e918.png)

2021-01-21 21:13 UTC, codingcodymiller requested changes
Hey Kenn! Great work so far, please see my notes:

2021-01-21 21:13 UTC, codingcodymiller commented on css-brochure-form/css-brochure-form/index.html
> +    <label id="labels" for="company email">COMPANY EMAIL</label>
This is a child of the `div`, so it should be indented.

2021-01-21 21:13 UTC, codingcodymiller commented on css-brochure-form/css-brochure-form/index.html
> +    <label  for="name">NAME</label>
This is a child of the `div`, so it should be indented.

2021-01-21 21:13 UTC, codingcodymiller commented on css-brochure-form/css-brochure-form/index.html
> +    <label  for="hiring">WHERE ARE YOU HIRING?</label>
This is a child of the `div`, so it should be indented.

2021-01-21 21:13 UTC, codingcodymiller commented on css-brochure-form/css-brochure-form/index.html
> +
You can remove empty lines between elements in html documents.

2021-01-21 21:13 UTC, codingcodymiller commented on css-brochure-form/css-brochure-form/styles.css
> +}
I don't know why you are doing this, but it can be removed. As a rule, you should never limit the size of the `body` element.

2021-01-21 21:13 UTC, codingcodymiller commented on css-brochure-form/css-brochure-form/styles.css
> +  text-align: left;
Please make sure all of your properties do something, and remove them if they don't. Look out for "CSS Roulette"! Every line of styling should be written with a clear purpose.

2021-01-21 21:13 UTC, codingcodymiller commented on css-brochure-form/css-brochure-form/styles.css
> +  src: url('BrandonGrotesque-Medium.woff2') format('woff2');
This can be removed, it does nothing here.

2021-01-21 21:13 UTC, codingcodymiller commented on css-brochure-form/css-brochure-form/styles.css
> +  src: url('BrandonGrotesque-Regular.woff2') format('woff2');
Please confirm that these are actually doing something :grin:

2021-01-21 21:13 UTC, codingcodymiller commented on css-brochure-form/css-brochure-form/styles.css
> +  src: url('BrandonGrotesque-Medium.woff2') format('woff2');
This can be removed.

2021-01-21 21:13 UTC, codingcodymiller commented on css-brochure-form/css-brochure-form/styles.css
> +  margin-left: 400px;
😱 😱 😱 😱 😱 

WOAH, that's a lot of margin! Are you using this to center the element? If so, there is a less intensive way to do it. You can set a width on this element, then apply `margin: auto` to it. In this case, the margin value is being adapted on either side of the element based on how much available space there is. Though both solutions make use of margin, this form of doing so is less manual, and as such easier to adapt in the future, if necessary.

2021-01-21 21:13 UTC, codingcodymiller commented on css-brochure-form/css-brochure-form/styles.css
> +  src: url('BrandonGrotesque-Medium.woff2') format('woff2');
This can be removed.

2021-02-21 20:43 UTC, thebearingedge approved these changes

2021-02-22 04:40 UTC, merged