Css three column layout
KennethDelaCruz/c0121-code-solutions pull request #19
Opened 2021-01-22 03:51 UTC by KennethDelaCruz

![image](https://user-images.githubusercontent.com/69921839/105444074-0a840600-5c22-11eb-9cad-4665f7dfe379.png)

2021-01-23 01:13 UTC, codingcodymiller requested changes
Hey Kenneth! This does not match the example image, please make sure that your output looks the same as the example

2021-01-26 23:22 UTC, codingcodymiller requested changes
Hey Kenn! Please attach a screenshot of your revised layout

2021-01-26 23:23 UTC, KennethDelaCruz commented
Sorry about that Cody.. Here you go!

![image](https://user-images.githubusercontent.com/69921839/105919408-75e72280-5fea-11eb-8537-f2fc57de0776.png)

2021-02-05 16:02 UTC, thebearingedge approved these changes

2021-02-06 01:11 UTC, merged