completed css-two-column-layout
KennethDelaCruz/c0121-code-solutions pull request #21
Opened 2021-01-23 01:01 UTC by KennethDelaCruz

![image](https://user-images.githubusercontent.com/69921839/105563585-71152c80-5cd3-11eb-805d-544cc4cc0621.png)

2021-01-23 01:52 UTC, codingcodymiller requested changes
Hey Kenneth! This doesn't match the example image, please revise this to match the example. For instance, your images are too small as compared to the rest of the layout

2021-01-27 02:39 UTC, codingcodymiller requested changes
Hey Kenn! Please provide a new image of your output after the revisions you've done

2021-01-27 02:40 UTC, KennethDelaCruz commented
Sorry again cody... but here you go!
![image](https://user-images.githubusercontent.com/69921839/105934936-f2d3c580-6005-11eb-9737-9969e0869a35.png)

2021-02-05 16:04 UTC, thebearingedge approved these changes

2021-02-06 01:10 UTC, merged