javascript-loops
KennethDelaCruz/c0121-code-solutions pull request #31
Opened 2021-01-28 20:44 UTC by KennethDelaCruz

![image](https://user-images.githubusercontent.com/69921839/106196672-93d99200-6166-11eb-90e7-6bcd34f3bd5d.png)

2021-01-28 22:47 UTC, codingcodymiller requested changes
Hey Kenn! A couple changes here. Also, you have `const` and `let` in your code. Did you do this deliberately, or was it changed by your text editor? You may still need to complete proper configuration of your `.eslintrc` file, or you still need to merge the pull request that includes that change. Please maker sure to merge any approved pull requests

2021-01-28 22:47 UTC, codingcodymiller commented on javascript-loops/main.js
> +  }
This should be a `while` loop

2021-01-28 22:47 UTC, codingcodymiller commented on javascript-loops/main.js
> +  }
This should be a `while` loop

2021-01-28 23:23 UTC, KennethDelaCruz commented
Hi Cody, The changes for the Const and Let were not intentional. It was probably the text editor. I went back and merged all the exercises that need to be merged. Hopefully that fixes it.

2021-01-29 05:30 UTC, KennethDelaCruz commented
here are the two changes that you have asked for. I have also changed all the let/const be changed to vars again. 

![image](https://user-images.githubusercontent.com/69921839/106235633-ec814d00-61af-11eb-945d-826eb98ce051.png)
![image](https://user-images.githubusercontent.com/69921839/106235640-f0ad6a80-61af-11eb-9e1c-5a4c4cde078d.png)

2021-01-29 20:39 UTC, codingcodymiller approved these changes
🙌

2021-01-30 23:45 UTC, merged