completed javascript forms
KennethDelaCruz/c0121-code-solutions pull request #41
Opened 2021-02-03 21:10 UTC by KennethDelaCruz

![image](https://user-images.githubusercontent.com/69921839/106809977-32f80100-6621-11eb-9582-9b8ca5b279e6.png)

2021-02-03 21:12 UTC, KennethDelaCruz commented
forgot to add the first photo!
![image](https://user-images.githubusercontent.com/69921839/106810211-7d797d80-6621-11eb-8656-7ef5b5a6dbec.png)

2021-02-03 21:14 UTC, codingcodymiller requested changes
Nice work so far! A couple notes:

2021-02-03 21:14 UTC, codingcodymiller commented on javascript-forms/form-events.js
> +console.log();
❓ ❓ ❓ ❓ ❓

2021-02-03 21:14 UTC, codingcodymiller commented on javascript-forms/form-values.js
> +var formRoute = document.querySelector('form');
This can be removed

2021-02-04 01:03 UTC, codingcodymiller requested changes
One more change!

2021-02-04 01:03 UTC, codingcodymiller commented on javascript-forms/form-values.js
> +  document.querySelector('form').reset();
You can just use `contactForm` instead of querying the DOM again

2021-02-04 01:05 UTC, codingcodymiller approved these changes
👏 👏 👏

2021-02-04 01:05 UTC, merged